remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme


title: [Smart Home]
description: [The intelligent home application for the ECE513 project at University of Arizona]

github:
  is_project_page: false
  zip_url: https://www.lgcyaxi.com
  another_url: https://www.lgcyaxi.com