remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme


title: [Smart Home]
description: [It is an Intelligent Home Application of ECE513 project for Team 16 at the University of Arizona.]
show_downloads: [true]

github:
  # is_project_page: false
  zip_url: https://github.com/usleolihao/ECE513_IOT_Project/raw/main/docs/Particle.zip